name: Deploy Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Prepare site
        run: |
         mkdir -p site
         cp docs/index.html site/
         for dir in linux docker kubernetes jenkins aws
         do
          if [ -d "$dir" ]; then
           mkdir -p site/$dir
           # Convert markdown files to HTML
           find $dir -name "*.md" | while read file
           do
            output=$(basename "$file" .md).html
            
            pandoc "$file" \
             -s \
             -o "site/$dir/$output"
             done
             
             # Copy existing HTML files
             find $dir -name "*.html" -exec cp {} site/$dir/ \;
          fi
          done

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v5